### ISSUE TITLE
Can't be reliably used for key generation

### ISSUE THREAD

**Issue by maciejmyslinski** [Tomekmularczyk/react-id-generator#10]
Hey!
Thank you for creating this library.
I want to report I use `useId` to generate ids for my elements and then wanted to use these ids as keys but when number of elements increases by more than 1, React throws an error that some elements don't have unique `key` prop.

That's because on first render `useId` doesn't actually generate more `id`. It only happens on the second rerender.

Here is [the demo](https://react-urfpj5.stackblitz.io) and here is a [source code](https://stackblitz.com/edit/react-urfpj5).

**Comment by Tomekmularczyk** [comment]
Thanks @maciejmyslinski I will take a look :)

**Comment by Tomekmularczyk** [comment]
@maciejmyslinski this should have been fixed with v2.0.2. With the next version, I think I'm going to remove dependencies list argument and just regenerate id's when the first argument of `useId` changes.

**Comment by maciejmyslinski** [comment]
awesome! 🔥
